
<!-- Botonera de navegación/alta -->
<div class="d-flex justify-content-center">
    <button class="btn btn-primary mt-2"     disabled><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;Anterior página</button> &nbsp;

    <a href="showAddUsuario" class="btn btn-primary mt-2"><i class="fa fa-user-plus" aria-hidden="true"></i> &nbsp; Alta usuario</a> &nbsp;    

    <button class="btn btn-primary mt-2"     disabled>Siguiente página&nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></button>
</div>
