<?php require 'templates/layout/header.phtml' ?>

<h2>Alta de nuevo usuario:</h2>

<!-- formulario de alta de usuario -->
<form method='POST' action='addUsuario'>
    <div class='form-group'>
        <label for='nombreusuario'>Usuario</label>
        <input type='text' class='form-control' id='nombreusuario' name='nombreusuario' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary mt-3'><i class="fa fa-check" aria-hidden="true"></i> &nbsp; Alta</button>
    <a href="showUsuarios" class="btn btn-primary mt-3"><i class="fa fa-times" aria-hidden="true"></i> &nbsp; Cancelar</a>
</form>

<?php require 'templates/layout/footer.phtml' ?>
