<?php require 'templates/layout/header.phtml' ?>

<h2>Alta de nuevo género:</h2>

<!-- formulario de alta de géneros -->
<form action="addGenero" method="POST" class="my-4">
    <div class="column">
        <div class="col-9">
            <div class="form-group">
                <label>Género</label>
                <input required name="genero" type="text" class="form-control">
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-success mt-2"><i class="fa fa-check" aria-hidden="true"></i> &nbsp; Alta</button>
    <a href="showGeneros" class="btn btn-primary mt-2"><i class="fa fa-times" aria-hidden="true"></i> &nbsp; Cancelar</a>
</form>

<?php require 'templates/layout/footer.phtml' ?>
