<?php require 'templates/layout/header.phtml' ?>

<h2>Está por eliminar el género:</h2>

<!-- formulario de confirmación de borrado de género -->
<form action="deleteGenero/<?=$genero->idgenero?>" method="POST" class="my-4">
    <div class="column">
        <div class="col-9">
            <div class="form-group">
                <label>Género</label>
                <input required name="genero" type="text" class="form-control" value="<?=$genero->genero?>" readonly>
            </div>
        </div>
    </div>

    <button type="submit"  class="btn btn-primary btn-danger mt-2">Eliminar</button>
    <a href="showGeneros" class="btn btn-primary mt-2">Cancelar</a>
</form>

<?php require 'templates/layout/footer.phtml' ?>