<?php require 'templates/layout/header.phtml' ?>

<h2>Lista de Usuarios</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Usuario</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="table-group-divider"> 

        <?php foreach($usuarios as $usuario): ?>
            <tr que_id="<?=$usuario->idusuario?>">
                <td data-label="Usuario"> <?=htmlspecialchars($usuario->nombreusuario)?> </td>

                <td data-label="Acciones">
                        <a href="showEditUsuario/<?=$usuario->idusuario?>"   class="btn btn-sm btn-success"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        &nbsp; 
                        <a href="showDeleteUsuario/<?=$usuario->idusuario?>" class="btn btn-sm btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                </td>
            </tr>
        <?php endforeach; ?> 

    </tbody>
</table>

<p class="mt-3"><small>Mostrando <?=$count?> usuarios</small></p>
<p id="mensaje"></p>

<?php require 'templates/barra_inferior_usuarios.phtml' ?>

<?php require 'templates/layout/footer.phtml' ?>
