<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!------ bootstrap ------>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!----- iconos de fontawesome ---->
    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
    <title>Biblioteca</title>
    <!----- icono para la pestaña ---->
    <link rel="shortcut icon" href="favicon/biblioteca.ico" type="image/x-icon">
    
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="">Biblioteca</a>
                
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="showLibros">Libros</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="showAutores">Autores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="showGeneros">Géneros</a>
                        </li>
                        <?php if(isset($_SESSION['nombreusuario'])): // si tiene usuario, es decir, si está logueado ?>
                            <li class="nav-item">
                                <a class="nav-link" href="showUsuarios">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="logout">Logout</a>
                            </li>
                        <?php else: // si no esta logueado ?>
                            <li class="nav-item">
                                <a class="nav-link" href="showLogin">Login</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
                
                <?php if(isset($_SESSION['nombreusuario'])): // si tiene usuario, es decir, si está logueado ?>
                    <span class="navbar-text"><?=htmlspecialchars( $_SESSION['nombreusuario'] )?></span>
                <?php endif; ?>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>

    <!-- <h1>&nbsp;</h1> -->
    <main class="container mt-3">
